### ISSUE TITLE
Add filecache back to stackage

### ISSUE THREAD

**Issue by PierreR** [bartavelle/filecache#8]
I would be nice to get filecache to stackage-nightly back so we can try to get back language-puppet in there for the next LTS. 
Maybe merging https://github.com/bartavelle/filecache/pull/7 could help.
Thanks.

**Comment by bartavelle** [comment]
I am not sure it is sustainable to have language-puppet in stackage, nor that it is overly useful. All its dependencies should be in though. As nothing (usually) depends on it, you can still stack-install it.

**Comment by PierreR** [comment]
Ok no problem.

I was using nix and its cache to distribute the executable. It was important to have language-puppet in stackage because that's how it got to the nix (hydra) cache.

I am using `cachix` these days so I don't mind anymore about either stackage or nix cache.

**Comment by bartavelle** [comment]
ah, right! Well, you can add language-puppet in stackage as soon as filecache is back!

**Comment by bartavelle** [comment]
so it's on hackage, I'll look into putting it into stackage later

**Comment by PierreR** [comment]
Done here : https://github.com/commercialhaskell/stackage/pull/4184

**Comment by bartavelle** [comment]
Oh wow thank you so much !!!!
